--
-- PostgreSQL database dump
--

-- Dumped from database version 14.1
-- Dumped by pg_dump version 14.3

-- Started on 2022-08-18 10:23:46

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE postgres;
--
-- TOC entry 3108 (class 1262 OID 12974)
-- Name: postgres; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE postgres WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'C.UTF-8';


ALTER DATABASE postgres OWNER TO postgres;

\connect postgres

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3109 (class 0 OID 0)
-- Dependencies: 3108
-- Name: DATABASE postgres; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON DATABASE postgres IS 'default administrative connection database';


--
-- TOC entry 3111 (class 0 OID 0)
-- Name: postgres; Type: DATABASE PROPERTIES; Schema: -; Owner: postgres
--

ALTER DATABASE postgres SET "app.settings.jwt_secret" TO 'a6IDJvR2GbiSi90Z/cEj6AiWcsifeAc/pdXHGa30hha3GpRdS4BIsTlw/0eVsabKBQ/704RCiIfwR3YzoyN+jQ==';
ALTER DATABASE postgres SET "app.settings.jwt_exp" TO '3600';


\connect postgres

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 14 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO postgres;

--
-- TOC entry 3112 (class 0 OID 0)
-- Dependencies: 14
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 278 (class 1259 OID 17774)
-- Name: cart; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.cart (
    id integer NOT NULL,
    product_id integer,
    user_id integer
);


ALTER TABLE public.cart OWNER TO supabase_admin;

--
-- TOC entry 279 (class 1259 OID 17777)
-- Name: cart_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 282 (class 1259 OID 17809)
-- Name: category; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.category (
    id integer NOT NULL,
    category_name character varying,
    product_id integer
);


ALTER TABLE public.category OWNER TO supabase_admin;

--
-- TOC entry 283 (class 1259 OID 17812)
-- Name: category_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 280 (class 1259 OID 17783)
-- Name: chat; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.chat (
    id integer NOT NULL,
    user_id integer,
    message text
);


ALTER TABLE public.chat OWNER TO supabase_admin;

--
-- TOC entry 281 (class 1259 OID 17786)
-- Name: chat_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.chat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 270 (class 1259 OID 17735)
-- Name: favorit; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.favorit (
    id integer NOT NULL,
    product_id integer,
    user_id integer
);


ALTER TABLE public.favorit OWNER TO supabase_admin;

--
-- TOC entry 271 (class 1259 OID 17738)
-- Name: favorit_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.favorit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 276 (class 1259 OID 17765)
-- Name: order; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public."order" (
    id integer NOT NULL,
    user_id integer,
    quantity bigint,
    payment_id integer
);


ALTER TABLE public."order" OWNER TO supabase_admin;

--
-- TOC entry 277 (class 1259 OID 17768)
-- Name: order_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public."order" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 274 (class 1259 OID 17754)
-- Name: payment; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.payment (
    id integer NOT NULL,
    order_id integer,
    total_price bigint,
    payment_status character varying
);


ALTER TABLE public.payment OWNER TO supabase_admin;

--
-- TOC entry 275 (class 1259 OID 17757)
-- Name: payment_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 264 (class 1259 OID 17702)
-- Name: product; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.product (
    id integer NOT NULL,
    product_detail_id integer,
    category_id integer
);


ALTER TABLE public.product OWNER TO supabase_admin;

--
-- TOC entry 266 (class 1259 OID 17712)
-- Name: product_details; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.product_details (
    id integer NOT NULL,
    product_name character varying,
    product_desc text,
    product_stock integer DEFAULT 0,
    product_condition character varying,
    product_picture character varying,
    product_price bigint
);


ALTER TABLE public.product_details OWNER TO supabase_admin;

--
-- TOC entry 267 (class 1259 OID 17715)
-- Name: product_details_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.product_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 265 (class 1259 OID 17705)
-- Name: product_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 268 (class 1259 OID 17724)
-- Name: profile; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.profile (
    id integer NOT NULL,
    user_id integer,
    gender character varying,
    store_name character varying,
    store_desc text
);


ALTER TABLE public.profile OWNER TO supabase_admin;

--
-- TOC entry 269 (class 1259 OID 17727)
-- Name: profile_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 262 (class 1259 OID 17689)
-- Name: user; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public."user" (
    id integer NOT NULL,
    email character varying,
    password character varying,
    roles character varying
);


ALTER TABLE public."user" OWNER TO supabase_admin;

--
-- TOC entry 263 (class 1259 OID 17692)
-- Name: user_seller_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_seller_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 272 (class 1259 OID 17745)
-- Name: wishlist; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.wishlist (
    id integer NOT NULL,
    product_id integer,
    user_id integer
);


ALTER TABLE public.wishlist OWNER TO supabase_admin;

--
-- TOC entry 273 (class 1259 OID 17748)
-- Name: wishlist_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.wishlist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wishlist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3097 (class 0 OID 17774)
-- Dependencies: 278
-- Data for Name: cart; Type: TABLE DATA; Schema: public; Owner: supabase_admin
--

COPY public.cart (id, product_id, user_id) FROM stdin;
\.


--
-- TOC entry 3101 (class 0 OID 17809)
-- Dependencies: 282
-- Data for Name: category; Type: TABLE DATA; Schema: public; Owner: supabase_admin
--

COPY public.category (id, category_name, product_id) FROM stdin;
\.


--
-- TOC entry 3099 (class 0 OID 17783)
-- Dependencies: 280
-- Data for Name: chat; Type: TABLE DATA; Schema: public; Owner: supabase_admin
--

COPY public.chat (id, user_id, message) FROM stdin;
\.


--
-- TOC entry 3089 (class 0 OID 17735)
-- Dependencies: 270
-- Data for Name: favorit; Type: TABLE DATA; Schema: public; Owner: supabase_admin
--

COPY public.favorit (id, product_id, user_id) FROM stdin;
\.


--
-- TOC entry 3095 (class 0 OID 17765)
-- Dependencies: 276
-- Data for Name: order; Type: TABLE DATA; Schema: public; Owner: supabase_admin
--

COPY public."order" (id, user_id, quantity, payment_id) FROM stdin;
\.


--
-- TOC entry 3093 (class 0 OID 17754)
-- Dependencies: 274
-- Data for Name: payment; Type: TABLE DATA; Schema: public; Owner: supabase_admin
--

COPY public.payment (id, order_id, total_price, payment_status) FROM stdin;
\.


--
-- TOC entry 3083 (class 0 OID 17702)
-- Dependencies: 264
-- Data for Name: product; Type: TABLE DATA; Schema: public; Owner: supabase_admin
--

COPY public.product (id, product_detail_id, category_id) FROM stdin;
\.


--
-- TOC entry 3085 (class 0 OID 17712)
-- Dependencies: 266
-- Data for Name: product_details; Type: TABLE DATA; Schema: public; Owner: supabase_admin
--

COPY public.product_details (id, product_name, product_desc, product_stock, product_condition, product_picture, product_price) FROM stdin;
\.


--
-- TOC entry 3087 (class 0 OID 17724)
-- Dependencies: 268
-- Data for Name: profile; Type: TABLE DATA; Schema: public; Owner: supabase_admin
--

COPY public.profile (id, user_id, gender, store_name, store_desc) FROM stdin;
\.


--
-- TOC entry 3081 (class 0 OID 17689)
-- Dependencies: 262
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: supabase_admin
--

COPY public."user" (id, email, password, roles) FROM stdin;
\.


--
-- TOC entry 3091 (class 0 OID 17745)
-- Dependencies: 272
-- Data for Name: wishlist; Type: TABLE DATA; Schema: public; Owner: supabase_admin
--

COPY public.wishlist (id, product_id, user_id) FROM stdin;
\.


--
-- TOC entry 3136 (class 0 OID 0)
-- Dependencies: 279
-- Name: cart_id_seq; Type: SEQUENCE SET; Schema: public; Owner: supabase_admin
--

SELECT pg_catalog.setval('public.cart_id_seq', 1, false);


--
-- TOC entry 3137 (class 0 OID 0)
-- Dependencies: 283
-- Name: category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: supabase_admin
--

SELECT pg_catalog.setval('public.category_id_seq', 1, false);


--
-- TOC entry 3138 (class 0 OID 0)
-- Dependencies: 281
-- Name: chat_id_seq; Type: SEQUENCE SET; Schema: public; Owner: supabase_admin
--

SELECT pg_catalog.setval('public.chat_id_seq', 1, false);


--
-- TOC entry 3139 (class 0 OID 0)
-- Dependencies: 271
-- Name: favorit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: supabase_admin
--

SELECT pg_catalog.setval('public.favorit_id_seq', 1, false);


--
-- TOC entry 3140 (class 0 OID 0)
-- Dependencies: 277
-- Name: order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: supabase_admin
--

SELECT pg_catalog.setval('public.order_id_seq', 1, false);


--
-- TOC entry 3141 (class 0 OID 0)
-- Dependencies: 275
-- Name: payment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: supabase_admin
--

SELECT pg_catalog.setval('public.payment_id_seq', 1, false);


--
-- TOC entry 3142 (class 0 OID 0)
-- Dependencies: 267
-- Name: product_details_id_seq; Type: SEQUENCE SET; Schema: public; Owner: supabase_admin
--

SELECT pg_catalog.setval('public.product_details_id_seq', 1, false);


--
-- TOC entry 3143 (class 0 OID 0)
-- Dependencies: 265
-- Name: product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: supabase_admin
--

SELECT pg_catalog.setval('public.product_id_seq', 1, false);


--
-- TOC entry 3144 (class 0 OID 0)
-- Dependencies: 269
-- Name: profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: supabase_admin
--

SELECT pg_catalog.setval('public.profile_id_seq', 1, false);


--
-- TOC entry 3145 (class 0 OID 0)
-- Dependencies: 263
-- Name: user_seller_id_seq; Type: SEQUENCE SET; Schema: public; Owner: supabase_admin
--

SELECT pg_catalog.setval('public.user_seller_id_seq', 1, false);


--
-- TOC entry 3146 (class 0 OID 0)
-- Dependencies: 273
-- Name: wishlist_id_seq; Type: SEQUENCE SET; Schema: public; Owner: supabase_admin
--

SELECT pg_catalog.setval('public.wishlist_id_seq', 1, false);


--
-- TOC entry 2911 (class 2606 OID 17885)
-- Name: cart cart_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.cart
    ADD CONSTRAINT cart_pkey PRIMARY KEY (id);


--
-- TOC entry 2915 (class 2606 OID 17892)
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id);


--
-- TOC entry 2913 (class 2606 OID 17906)
-- Name: chat chat_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT chat_pkey PRIMARY KEY (id);


--
-- TOC entry 2903 (class 2606 OID 17915)
-- Name: favorit favorit_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.favorit
    ADD CONSTRAINT favorit_pkey PRIMARY KEY (id);


--
-- TOC entry 2909 (class 2606 OID 17962)
-- Name: order order_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT order_pkey PRIMARY KEY (id);


--
-- TOC entry 2907 (class 2606 OID 18094)
-- Name: payment payment_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_pkey PRIMARY KEY (id);


--
-- TOC entry 2899 (class 2606 OID 17975)
-- Name: product_details product_details_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.product_details
    ADD CONSTRAINT product_details_pkey PRIMARY KEY (id);


--
-- TOC entry 2897 (class 2606 OID 18030)
-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);


--
-- TOC entry 2901 (class 2606 OID 17984)
-- Name: profile profile_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.profile
    ADD CONSTRAINT profile_pkey PRIMARY KEY (id);


--
-- TOC entry 2893 (class 2606 OID 17697)
-- Name: user user_seller_email_key; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_seller_email_key UNIQUE (email);


--
-- TOC entry 2895 (class 2606 OID 17922)
-- Name: user user_seller_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_seller_pkey PRIMARY KEY (id);


--
-- TOC entry 2905 (class 2606 OID 18009)
-- Name: wishlist wishlist_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.wishlist
    ADD CONSTRAINT wishlist_pkey PRIMARY KEY (id);


--
-- TOC entry 2926 (class 2606 OID 18220)
-- Name: cart cart_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.cart
    ADD CONSTRAINT cart_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.product(id);


--
-- TOC entry 2927 (class 2606 OID 18234)
-- Name: cart cart_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.cart
    ADD CONSTRAINT cart_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- TOC entry 2929 (class 2606 OID 18206)
-- Name: category category_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.product(id);


--
-- TOC entry 2928 (class 2606 OID 18190)
-- Name: chat chat_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT chat_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- TOC entry 2919 (class 2606 OID 18159)
-- Name: favorit favorit_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.favorit
    ADD CONSTRAINT favorit_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.product(id);


--
-- TOC entry 2920 (class 2606 OID 18173)
-- Name: favorit favorit_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.favorit
    ADD CONSTRAINT favorit_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- TOC entry 2924 (class 2606 OID 18145)
-- Name: order order_payment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT order_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payment(id);


--
-- TOC entry 2925 (class 2606 OID 18131)
-- Name: order order_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT order_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- TOC entry 2923 (class 2606 OID 18117)
-- Name: payment payment_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_order_id_fkey FOREIGN KEY (order_id) REFERENCES public."order"(id);


--
-- TOC entry 2916 (class 2606 OID 18087)
-- Name: product product_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.category(id);


--
-- TOC entry 2917 (class 2606 OID 18073)
-- Name: product product_product_detail_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_product_detail_id_fkey FOREIGN KEY (product_detail_id) REFERENCES public.product_details(id);


--
-- TOC entry 2918 (class 2606 OID 18002)
-- Name: profile profile_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.profile
    ADD CONSTRAINT profile_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- TOC entry 2921 (class 2606 OID 18059)
-- Name: wishlist wishlist_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.wishlist
    ADD CONSTRAINT wishlist_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.product(id);


--
-- TOC entry 2922 (class 2606 OID 18023)
-- Name: wishlist wishlist_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.wishlist
    ADD CONSTRAINT wishlist_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- TOC entry 3110 (class 0 OID 0)
-- Dependencies: 3108
-- Name: DATABASE postgres; Type: ACL; Schema: -; Owner: postgres
--

GRANT ALL ON DATABASE postgres TO dashboard_user;


--
-- TOC entry 3113 (class 0 OID 0)
-- Dependencies: 14
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;


--
-- TOC entry 3114 (class 0 OID 0)
-- Dependencies: 278
-- Name: TABLE cart; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.cart TO postgres;
GRANT ALL ON TABLE public.cart TO anon;
GRANT ALL ON TABLE public.cart TO authenticated;
GRANT ALL ON TABLE public.cart TO service_role;


--
-- TOC entry 3115 (class 0 OID 0)
-- Dependencies: 279
-- Name: SEQUENCE cart_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.cart_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.cart_id_seq TO anon;
GRANT ALL ON SEQUENCE public.cart_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.cart_id_seq TO service_role;


--
-- TOC entry 3116 (class 0 OID 0)
-- Dependencies: 282
-- Name: TABLE category; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.category TO postgres;
GRANT ALL ON TABLE public.category TO anon;
GRANT ALL ON TABLE public.category TO authenticated;
GRANT ALL ON TABLE public.category TO service_role;


--
-- TOC entry 3117 (class 0 OID 0)
-- Dependencies: 283
-- Name: SEQUENCE category_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.category_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.category_id_seq TO anon;
GRANT ALL ON SEQUENCE public.category_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.category_id_seq TO service_role;


--
-- TOC entry 3118 (class 0 OID 0)
-- Dependencies: 280
-- Name: TABLE chat; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.chat TO postgres;
GRANT ALL ON TABLE public.chat TO anon;
GRANT ALL ON TABLE public.chat TO authenticated;
GRANT ALL ON TABLE public.chat TO service_role;


--
-- TOC entry 3119 (class 0 OID 0)
-- Dependencies: 281
-- Name: SEQUENCE chat_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.chat_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.chat_id_seq TO anon;
GRANT ALL ON SEQUENCE public.chat_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.chat_id_seq TO service_role;


--
-- TOC entry 3120 (class 0 OID 0)
-- Dependencies: 270
-- Name: TABLE favorit; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.favorit TO postgres;
GRANT ALL ON TABLE public.favorit TO anon;
GRANT ALL ON TABLE public.favorit TO authenticated;
GRANT ALL ON TABLE public.favorit TO service_role;


--
-- TOC entry 3121 (class 0 OID 0)
-- Dependencies: 271
-- Name: SEQUENCE favorit_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.favorit_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.favorit_id_seq TO anon;
GRANT ALL ON SEQUENCE public.favorit_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.favorit_id_seq TO service_role;


--
-- TOC entry 3122 (class 0 OID 0)
-- Dependencies: 276
-- Name: TABLE "order"; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public."order" TO postgres;
GRANT ALL ON TABLE public."order" TO anon;
GRANT ALL ON TABLE public."order" TO authenticated;
GRANT ALL ON TABLE public."order" TO service_role;


--
-- TOC entry 3123 (class 0 OID 0)
-- Dependencies: 277
-- Name: SEQUENCE order_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.order_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.order_id_seq TO anon;
GRANT ALL ON SEQUENCE public.order_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.order_id_seq TO service_role;


--
-- TOC entry 3124 (class 0 OID 0)
-- Dependencies: 274
-- Name: TABLE payment; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.payment TO postgres;
GRANT ALL ON TABLE public.payment TO anon;
GRANT ALL ON TABLE public.payment TO authenticated;
GRANT ALL ON TABLE public.payment TO service_role;


--
-- TOC entry 3125 (class 0 OID 0)
-- Dependencies: 275
-- Name: SEQUENCE payment_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.payment_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.payment_id_seq TO anon;
GRANT ALL ON SEQUENCE public.payment_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.payment_id_seq TO service_role;


--
-- TOC entry 3126 (class 0 OID 0)
-- Dependencies: 264
-- Name: TABLE product; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.product TO postgres;
GRANT ALL ON TABLE public.product TO anon;
GRANT ALL ON TABLE public.product TO authenticated;
GRANT ALL ON TABLE public.product TO service_role;


--
-- TOC entry 3127 (class 0 OID 0)
-- Dependencies: 266
-- Name: TABLE product_details; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.product_details TO postgres;
GRANT ALL ON TABLE public.product_details TO anon;
GRANT ALL ON TABLE public.product_details TO authenticated;
GRANT ALL ON TABLE public.product_details TO service_role;


--
-- TOC entry 3128 (class 0 OID 0)
-- Dependencies: 267
-- Name: SEQUENCE product_details_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.product_details_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.product_details_id_seq TO anon;
GRANT ALL ON SEQUENCE public.product_details_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.product_details_id_seq TO service_role;


--
-- TOC entry 3129 (class 0 OID 0)
-- Dependencies: 265
-- Name: SEQUENCE product_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.product_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.product_id_seq TO anon;
GRANT ALL ON SEQUENCE public.product_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.product_id_seq TO service_role;


--
-- TOC entry 3130 (class 0 OID 0)
-- Dependencies: 268
-- Name: TABLE profile; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.profile TO postgres;
GRANT ALL ON TABLE public.profile TO anon;
GRANT ALL ON TABLE public.profile TO authenticated;
GRANT ALL ON TABLE public.profile TO service_role;


--
-- TOC entry 3131 (class 0 OID 0)
-- Dependencies: 269
-- Name: SEQUENCE profile_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.profile_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.profile_id_seq TO anon;
GRANT ALL ON SEQUENCE public.profile_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.profile_id_seq TO service_role;


--
-- TOC entry 3132 (class 0 OID 0)
-- Dependencies: 262
-- Name: TABLE "user"; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public."user" TO postgres;
GRANT ALL ON TABLE public."user" TO anon;
GRANT ALL ON TABLE public."user" TO authenticated;
GRANT ALL ON TABLE public."user" TO service_role;


--
-- TOC entry 3133 (class 0 OID 0)
-- Dependencies: 263
-- Name: SEQUENCE user_seller_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.user_seller_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.user_seller_id_seq TO anon;
GRANT ALL ON SEQUENCE public.user_seller_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.user_seller_id_seq TO service_role;


--
-- TOC entry 3134 (class 0 OID 0)
-- Dependencies: 272
-- Name: TABLE wishlist; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.wishlist TO postgres;
GRANT ALL ON TABLE public.wishlist TO anon;
GRANT ALL ON TABLE public.wishlist TO authenticated;
GRANT ALL ON TABLE public.wishlist TO service_role;


--
-- TOC entry 3135 (class 0 OID 0)
-- Dependencies: 273
-- Name: SEQUENCE wishlist_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.wishlist_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.wishlist_id_seq TO anon;
GRANT ALL ON SEQUENCE public.wishlist_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.wishlist_id_seq TO service_role;


--
-- TOC entry 2504 (class 826 OID 16668)
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES  TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES  TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES  TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES  TO service_role;


--
-- TOC entry 2505 (class 826 OID 16669)
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES  TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES  TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES  TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES  TO service_role;


--
-- TOC entry 2503 (class 826 OID 16667)
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS  TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS  TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS  TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS  TO service_role;


--
-- TOC entry 2507 (class 826 OID 16671)
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS  TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS  TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS  TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS  TO service_role;


--
-- TOC entry 2502 (class 826 OID 16666)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES  TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES  TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES  TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES  TO service_role;


--
-- TOC entry 2506 (class 826 OID 16670)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES  TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES  TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES  TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES  TO service_role;


-- Completed on 2022-08-18 10:24:02

--
-- PostgreSQL database dump complete
--

